#!/bin/bash

set -x

function join_array {
  local delimiter=${1-}
  local values=${2-}
  
  if shift 2; then
    printf %s $values "${@/#/$delimiter}"
  fi
}

readarray repositories < <(curl -L   \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -H "Authorization: Bearer $(cat settings/api-token.txt)" \
    "https://api.github.com/orgs/wiremock/repos?type=sources&per_page=100" \
    | jq --raw-output '.[].name')

echo "${repositories[@]}" > settings/projects.lock

repoUrls=()
gitUrls=()
for repo in "${repositories[@]}"
do
  repoUrl="https://github.com/wiremock/${repo//[$'\t\r\n ']/}"
  repoUrls+="\"${repoUrl}\" "
  gitUrls+="\"${repoUrl}.git\" "
done

git_repos=$(join_array ",\n      " ${gitUrls[@]})
github_repos=$(join_array ",\n      " ${repoUrls[@]})

awk -v git="$git_repos" -v github="$github_repos" '{gsub(/\${GIT_REPOS}/,git); gsub(/\${GITHUB_REPOS}/,github)}2' settings/projects.json.template > settings/projects.json
