#!/bin/bash

GITHUB_API_TOKEN=$(cat /run/secrets/github-api-token)
awk -v token="$GITHUB_API_TOKEN" '{gsub(/\${GITHUB_TOKEN}/,token)}1' \
    /sirmordred-setup.cfg.template > /home/grimoire/conf/setup.cfg

${DEPLOY_USER_DIR}/stage
